# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85ca2651d46e124b35075ff0055629c14776bcaa60fb2c34b422af237eee5d00f5bbf1302e03656bd45009a27c025ca4b79fcead021ee2c844602a2e7516920d

test:
  secret_key_base: b520937d8651cbbdd54bbac2e32d624d3e04b2cb4cd98d44ba9ea86067d694c3fcdc2e3221c0434d65958cfa6860c7daca91d0f3e8c20e3d82ac8f22f6fa0ec5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
